name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    # 1. Vérifie le dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Connexion au registre Docker (GitHub Container Registry)
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 3. Construire l'image Docker
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/app:latest .

    # 4. Pousser l'image Docker sur GitHub Packages
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}/app:latest
